# Generated by Django 3.0.3 on 2020-02-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user_feedback", "0003_auto_20191220_1906")]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedback"},
        )
    ]
